version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      REDIS_URL: "redis://kar-redis/"
      # Todo check if user:password are in correct order
      DB_HOST: "postresql://${DATABASE_USER}:${DATABASE_PASS}@postgres"
      HOST_IP: "0.0.0.0"
      PORT: 5000
    depends_on:
      - redis
      - postgres
    ports:
      - "5000:5000"

  redis:
    image: woahbase/alpine-redis
    container_name: kar-redis
    ports:
      - "6379:6379" # Todo potentially close the port

  postgres:
    image: postgres:alpine

    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASS}"

#    restart: always
    ports:
      - "5432:5432" # Todo potentially close the port